### ISSUE TITLE
getPageUrl() name collision with docpad-plugin-services

### ISSUE THREAD

**Issue by jbelcher** [docpad/docpad-plugin-paged#10]
getNextPage() and getPrevPage() were not returning correct urls even though document.page data looked okay, and after debugging I saw that https://github.com/docpad/docpad-plugin-paged/blob/master/src/paged.plugin.coffee#L79 was actually calling the getPageUrl() defined in the services plugin: https://github.com/docpad/docpad-plugin-services/blob/master/src/services.plugin.coffee#L16

I'm able to work around this temporarily by just disabling the services plugin, but you may want to address that collision in case folks need to use both plugins.

**Comment by StormPooper** [comment]
I'd rather make a breaking change then leave the plugins incompatible, so I think we'll have to go ahead and rename them. I'll look into declaring an alias if it hasn't already been defined to maintain some form of backwards compatibility though.

**Comment by StormPooper** [comment]
Fixed, will be included in the next release of the plugin. I've made it define `getPageUrl` if it's not already defined and it warns the user that it's deprecated. If it's already defined, it'll warn the user of this. I think this is the best we can do without detecting specific plugins, which is a rabbit hole I don't want to head down.

**Comment by StormPooper** [comment]
Fixed in v2.4.0.
