### ISSUE TITLE
Generated redirect page doesn't validate

### ISSUE THREAD

**Issue by zenorocha** [docpad/docpad-plugin-paged#16]
If you try run some of the redirect test cases in [W3C Validator](http://validator.w3.org/) you get:

![](http://f.cl.ly/items/2y1u0P0l0B3l2q133p2q/Screen%20Shot%202014-02-11%20at%205.02.38%20PM.png)

Because it should have an extra space between `0;` and `url`:

``` html
<!-- Wrong -->
<meta http-equiv="REFRESH" content="0;url=/posts/awesome.1">`

<!-- Right -->
<meta http-equiv="REFRESH" content="0; url=/posts/awesome.1">
```

P.S.: I wanted to send a PR to fix this minor problem but I couldn't find where to add this space.

**Comment by StormPooper** [comment]
@zenorocha, the paged plugin is not responsible for the static redirection page creation, the cleanruls plugin is. I've created a pull request there for you: docpad/docpad-plugin-cleanurls#23

**Comment by balupton** [comment]
This has been merged, but not released.

**Comment by balupton** [comment]
This has since been released to the cleanurls plugin
