### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by musshush** [docpad/docpad-plugin-paged#9]
I've tried both "docpad inatall" and "npm inatall" but the following is the error message I'm getting.

npm http GET https://registry.npmjs.org/docpad-plugin-paged
npm http GET https://registry.npmjs.org/docpad-plugin-paged
npm http GET https://registry.npmjs.org/docpad-plugin-paged
npm ERR! Error: getaddrinfo EADDRINFO
npm ERR!     at errnoException (dns.js:37:11)
npm ERR!     at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "docpad-plugin-paged@2" "--save"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! syscall getaddrinfo
npm ERR! code EADDRINFO
npm ERR! errno EADDRINFO
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/npm-debug.log
npm ERR! not ok code 0
error: Something went wrong with the action
error: An error occured: 
Error: npm http GET https://registry.npmjs.org/docpad-plugin-paged
npm http GET https://registry.npmjs.org/docpad-plugin-paged
npm http GET https://registry.npmjs.org/docpad-plugin-paged
npm ERR! Error: getaddrinfo EADDRINFO
npm ERR!     at errnoException (dns.js:37:11)
npm ERR!     at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "docpad-plugin-paged@2" "--save"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! syscall getaddrinfo
npm ERR! code EADDRINFO
npm ERR! errno EADDRINFO
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/npm-debug.log
npm ERR! not ok code 0

    at ChildProcess.<anonymous> (/vagrant/node_modules/docpad/node_modules/safeps/out/lib/safeps.js:154:21)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)

**Comment by StormPooper** [comment]
@musshush not sure if you're still having this problem, but it looks like a network issue to me, or npm just acting up. Have you tried it again recently? If that still doesn't work, can you post your packages.json file?
